###
### Hill Category TOP
GET http://localhost:8080/munros?category=TOP

### Hill Category MUN
GET http://localhost:8080/munros?category=MUN

### Hill Category MUN
GET http://localhost:8080/munros?category=