###
### All null values
GET http://localhost:8080/munros

### Hill Category TOP
GET http://localhost:8080/munros?category=TOP

### Hill Category MUN,TOP
GET http://localhost:8080/munros?category=MUN,TOP

### min
GET http://localhost:8080/munros?min=926.2

### max
GET http://localhost:8080/munros?max=926.5

### min and max
GET http://localhost:8080/munros?min=900&max=930

### limit
GET http://localhost:8080/munros?limit=10

### sort=name,ASC&sort=height=DESC
GET http://localhost:8080/munros?sort=name,ASC&sort=height,DESC

### sort=height,ASC&sort=name=DESC
GET http://localhost:8080/munros?sort=height,ASC&sort=name,DESC